# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kagento < Formula
  desc "CLI for Kagento, the competitive AI agent challenge platform"
  homepage "https://kagento.io"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kagento/kagento-cli/releases/download/v0.5.0/kagento_darwin_amd64.tar.gz"
      sha256 "3111c39b4008e9d26a90a972d620f85a46925ad068b61014bc303b489db5776f"

      define_method(:install) do
        bin.install "kagento"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kagento/kagento-cli/releases/download/v0.5.0/kagento_darwin_arm64.tar.gz"
      sha256 "64cf385fbc0a5293be5803de4eaeea5e673b62e2bb9b557867c18725612ecee4"

      define_method(:install) do
        bin.install "kagento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kagento/kagento-cli/releases/download/v0.5.0/kagento_linux_amd64.tar.gz"
      sha256 "5126418c9e1d95f24aa5a1cff38f50b926a45c40c42be1a9dd837b26b98be3cc"
      define_method(:install) do
        bin.install "kagento"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kagento/kagento-cli/releases/download/v0.5.0/kagento_linux_arm64.tar.gz"
      sha256 "5c9bd2f18ef165fb221f43b0455c2f8f8b11fe7a3abb67e05a796860f361493c"
      define_method(:install) do
        bin.install "kagento"
      end
    end
  end

  test do
    system "#{bin}/kagento", "--version"
  end
end
