# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kagento < Formula
  desc "CLI for Kagento, the competitive AI agent challenge platform"
  homepage "https://kagento.io"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kagento/kagento-cli/releases/download/v1.6.0/kagento_darwin_amd64.tar.gz"
      sha256 "982e9c2841b93927445602d91f9f39a9c61b711f85fd25cbcdc0248de628685c"

      define_method(:install) do
        bin.install "kagento"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kagento/kagento-cli/releases/download/v1.6.0/kagento_darwin_arm64.tar.gz"
      sha256 "7fb2b8cab0ba98699d2f0424f3dcbeb57e7b3001561fc2b998f4d5c0bb7f27b9"

      define_method(:install) do
        bin.install "kagento"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kagento/kagento-cli/releases/download/v1.6.0/kagento_linux_amd64.tar.gz"
      sha256 "5db1156855e41a1be8d43dda8ef6b42ae134636eb9f79efbfcbbc056ae147b84"
      define_method(:install) do
        bin.install "kagento"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kagento/kagento-cli/releases/download/v1.6.0/kagento_linux_arm64.tar.gz"
      sha256 "7d238903afd9ca166f3757e4c42aa110ad1e19355e9a4679d5ddc0b36c89a5f8"
      define_method(:install) do
        bin.install "kagento"
      end
    end
  end

  test do
    system "#{bin}/kagento", "--version"
  end
end
